#Zookeeper and Kafka images refer to: https://github.com/confluentinc/cp-docker-images/blob/4.0.x/examples/kafka-cluster/docker-compose.yml

version: '2'
services:
  zookeeper-1:
    image: ipekuyguner/zookeeper:latest
    container_name: zookeeper-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"
    restart: unless-stopped
  zookeeper-2:
    image: ipekuyguner/zookeeper:latest
    container_name: zookeeper-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"
    restart: unless-stopped
  zookeeper-3:
    image: ipekuyguner/zookeeper:latest
    container_name: zookeeper-3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"
    restart: unless-stopped
  kafka-1:
    image: ipekuyguner/kafka:latest
    container_name: kafka-1
    network_mode: host
    ports:
      - 19092:19092
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://141.40.254.2:19092
    extra_hosts:
      - "moby:127.0.0.1"
    restart: unless-stopped
    
  kafka-2:
    image: ipekuyguner/kafka:latest
    container_name: kafka-2
    network_mode: host
    ports:
      - 29092:29092
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://141.40.254.2:29092
    extra_hosts:
      - "moby:127.0.0.1"
    restart: unless-stopped

  kafka-3:
    image: ipekuyguner/kafka:latest
    container_name: kafka-3
    network_mode: host
    ports:
      - 39092:39092
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://141.40.254.2:39092
    extra_hosts:
      - "moby:127.0.0.1"  
    restart: unless-stopped
    
  streams:
    image: ipekuyguner/datalayer
    container_name: Kafka-Streams-App
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      KAFKA_IP: 141.40.254.2
      ELASTIC_IP: 141.40.254.142
      KAFKA_INPUT_CHANNEL: sensor-input
      KAFKA_OUTPUT_CHANNEL: streams-sensor-output

  dashboard:
    image: ipekuyguner/dashboard
    container_name: dashboard
    ports:
      - 80:5000
    restart: unless-stopped
    
